"""Updates business models to match frontend data

Revision ID: 11676226c02d
Revises: ec84c90cdd1d
Create Date: 2024-10-20 19:20:18.202546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11676226c02d'
down_revision = 'ec84c90cdd1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('main_image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('additional_image_url1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('additional_image_url2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('additional_image_url3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('paragraph1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('paragraph2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('paragraph3', sa.Text(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_index('ix_business_ix_business_identifier')
        batch_op.create_index(batch_op.f('ix_business_name'), ['name'], unique=False)
        batch_op.drop_column('city')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('country')
        batch_op.drop_column('image_url')
        batch_op.drop_column('county')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('website')
        batch_op.drop_column('postal_address')
        batch_op.drop_column('price_range')
        batch_op.drop_column('hours')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hours', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price_range', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('postal_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('website', sa.VARCHAR(length=130), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('county', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_business_name'))
        batch_op.create_index('ix_business_ix_business_identifier', ['ix_business_identifier'], unique=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('paragraph3')
        batch_op.drop_column('paragraph2')
        batch_op.drop_column('paragraph1')
        batch_op.drop_column('additional_image_url3')
        batch_op.drop_column('additional_image_url2')
        batch_op.drop_column('additional_image_url1')
        batch_op.drop_column('main_image_url')
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
