"""adds a user action log

Revision ID: 1ad150f81ef2
Revises: a8c83fcab4c8
Create Date: 2024-11-01 16:44:32.115515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad150f81ef2'
down_revision = 'a8c83fcab4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('target_model', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_action_log_user_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_index('ix_business_name')
        batch_op.create_index(batch_op.f('ix_business_ix_business_identifier'), ['ix_business_identifier'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_ix_business_identifier'))
        batch_op.create_index('ix_business_name', ['name'], unique=False)

    op.drop_table('user_action_log')
    # ### end Alembic commands ###
