"""removes constraint on password length

Revision ID: 73977a8816d0
Revises: dfb1858c2e46
Create Date: 2024-10-20 17:54:51.641439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73977a8816d0'
down_revision = 'dfb1858c2e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_index('ix_business_ix_business_identifier')
        batch_op.create_index(batch_op.f('ix_business_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_name'))
        batch_op.create_index('ix_business_ix_business_identifier', ['ix_business_identifier'], unique=True)

    # ### end Alembic commands ###
