"""removes description column

Revision ID: d80f18eca0d0
Revises: 11676226c02d
Create Date: 2024-10-20 20:02:59.533139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80f18eca0d0'
down_revision = '11676226c02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_index('ix_business_name')
        batch_op.create_index(batch_op.f('ix_business_name'), ['name'], unique=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_business_name'))
        batch_op.create_index('ix_business_name', ['name'], unique=False)

    # ### end Alembic commands ###
